### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by acinader**
I have now tested this against ParsePlatform/parse-server#3080

if we merge ParsePlatform/parse-server#3080 then I can publish this.

@flovilmart can you take a peek

### CODE REVIEW

**Comment by acinader** [comment]
FYI, this wont pass tests since it is dependent on using parse-server with https://github.com/ParsePlatform/parse-server/pull/3080 which i have npm linked....

**Comment by flovilmart** [comment]
ah right shite :/ we could make either a build branch or merge this one

**Comment by acinader** [comment]
ok, a jury rigged a build branch on my fork of parse-server so we can get it to build and stuff.

on to the readme.

**Comment by flovilmart** [comment]
So if I get it correctly, this adapter will let anyone running 2+ parse-server in the cloud, leverage SQS to spread large amount of push across their cluster without doing anything??? THIS IS INSANE!

**Comment by acinader** [comment]
Ok, @flovilmart I tested this with my parse server.  and it actually worked.  cool.

I think I have addressed your comments, let me know.

Also, note: https://github.com/ParsePlatform/parse-server/pull/3080#pullrequestreview-15528847  which i had to hack around.....

**Comment by dvanwinkle** [comment]
@acinader I'm taking a stab at this now. Does it auto-handle both the consumer and producer roles with the config in the README?

**Comment by acinader** [comment]
@dvanwinkle oh boy, its been awhile...../me goes to read the source code.

Ok. so if i get your question, my code will 

a) not try to instantiate the queue so you'll need to set up the queue yourself.
b) will require that permissions are set.  I created a policy for the queue and added it to my dev user's group as well as to the role that i deploy with.

If you look at the spec, you'll see this test: 
`xit('a test for real that can be done against a live queue', (done) => {`

if you remote the x (or better yet, replace it with an f) you can then 
`npm test` and it'll just run that test and you can then make sure that you have the queue setup (in the case of the test the queue is named `foo`) and permission right.

by running the test, if you have any permissions problems, the message should be pretty clear as to what they are....

let me know if this is not responsive and if i can help.....

**Comment by dvanwinkle** [comment]
@acinader Thanks! Have you by chance published the NPM package yet?

**Comment by acinader** [comment]
is now....https://www.npmjs.com/package/parse-server-sqs-mq-adapter

**Comment by dvanwinkle** [comment]
@acinader Thanks! I think that you forgot to change the peer dependency ;-)

**Comment by acinader** [comment]
fixed.

**Pull request merged**
